### ISSUE TITLE
[Feature] Answer file to completely install Elementary OS without interaction

### ISSUE THREAD

**Issue by TeamLinux01** [elementary/installer#568] opened 2021-06-29 16:57 UTC
If the installer could support the ability to look at an answer file during installation to be able to fill in one/many/all the questions that would be required to do the install, it would help greatly for people who want to save time installing the OS or deploying to a lot of machines, such as OEMs or companies.

Things to consider would be what the file structure should look like, the default location for such a file should be and if it is possible to map that easily from an external source, what is used to generate such a file (maybe the installer itself could save the file on a normal install being finished and also have a tool available on an already installed eOS).

I personally like to use [Ventoy](https://www.ventoy.net/en/index.html) to install OSes, so if the file could be [injected into a location of the ISO](https://www.ventoy.net/en/plugin_injection.html) or be loaded from a USB partition that is formatted ExFAT, that would be helpful.

**Comment by swirly** [comment] 2021-09-07 13:21
Is this not a duplicate of #503 ?

**Closed** 2021-10-12 12:15 UTC
