### ISSUE TITLE
OS7 (stable) install: Custom partition window moved off-screen and could not be dragged back

### ISSUE THREAD

**Issue by jeremypw** [elementary/installer#683] opened 2023-02-07 18:13 UTC
### What Happened?

During custom partitioning, after modifying the partitions manually and returning to the custom partition view, attempted to adjust the window by dragging in the usual manner.  For some reason he window moved almost off-screen, just a small corner showed.  Attempts to move the window back by dragging did not move it.  Fortunately the "half-tile" keyboard shortcut worked and made the window usable again.

### Steps to Reproduce

Attempt to move the custom partition window by dragging.
It does not move as expected and may become undraggable.

### Expected Behavior

Windows presented during installation should be draggable as usual.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment] 2023-02-07 18:15
Duplicate of https://github.com/elementary/greeter/issues/632

It has to do with `always-center` and the compositor not handling that nicely

**Closed by danirabbit** 2023-02-07 18:15 UTC

**Comment by peteruithoven** [comment] 2023-02-15 15:25
Bit of a workaround for getting the window back: Pressing your windows key and then dragging the window.
