### ISSUE TITLE
elementary OS 6 installation hangs at 70% for various l18n settings

### ISSUE THREAD

**Issue by m93a** [elementary/installer#591] opened 2021-08-11 10:54 UTC
## What Happened
I've tried it on at least three computers and with three different versions of elementary OS 6 (Beta 2, RC, stable) and they all displayed the same behavior: if I choose Czech as the language of the installer, the installation hangs at 70 % and never finishes. Installing in English (US) fixes the problem.

## Steps to Reproduce

1. Download an Elementary OS .iso, put it on a flash drive and boot it
2. Choose “čeština” as the installer language
3. Go through the installation (the specific choices don't matter much, I've tried _Custom Installation_ as well as _Erase All_)
4. The installation hangs at “Nastavuje se systém (70 %)“

### Logs
The last output in the terminal is:
```
INFO: running "chroot" "/tmp/distinst.sbHpHHbIvPM7" "apt-get" "purge" "-y" "btrfs-progs" "casper" "cifs-utils"
"discover" "discover-data" "distinst" "dmraid" "elementary-live" "expect" "f2fs-tools" "fatresize" "finalrd"
"gettext" "gparted" "kpartx" "kpartx-boot" "libatkmn-1.6-1v5" "libcairomm-1.0-1v5" "libcroco3" "libdiscover2"
"libdistinst" "libdmraid1.0.0.rc16" "libf2fs-format4" "libf2fs5" "libglibmm-2.4-1v5" "libgtkmm-3.0-1v5"
"libnss-mymachines" "libpangomm-1.4-1v5" "libsigc++-2.0-0v5" "libtcl8.6" "libusb-0.1-4" "localechooseer-data"
"mokutil" "reiserfsprogs" "systemd-container" "tcl-expect" "tcl8.6" "user-setup" "wingpanel" "xfsprogs"
INFO:
INFO:
INFO: Načítají se stavové informace...
INFO: Následující balíky budou ODSTRANĚNY:
INFO:   btrfs-progs* casper* cifs-utils* discover* discover-data* distinst* dmraid*
INFO:   elementary-live* expect* f2fs-tools* fatresize* finalrd* gettext* gparted*
INFO:   kpartx* kpartx-boot* libatkmn-1.6-1v5* libcairomm-1.0-1v5* libcroco3*
INFO:   libdiscover2* libdistinst* libdmraid1.0.0.rc16* libf2fs-format4* libf2fs5*
INFO:   libglibmm-2.4-1v5* libgtkmm-3.0-1v5* libnss-mymachines* libpangomm-1.4-1v5*
INFO:   libsigc++-2.0-0v5* libtcl8.6* libusb-0.1-4* localechooseer-data* mokutil*
INFO:   reiserfsprogs* systemd-container* tcl-expect* tcl8.6* user-setup* wingpanel*
INFO:   xfsprogs*
INFO: 0 aktualizováno, 0 nově instalováno, 43 k odstranění a 0 neaktualizováno.
INFO: Po této operaci bude na disku uvolněno 47,3 MB.
```

Which roughly translates to:
```
...
INFO: Loading state information...
INFO: The following packages will be REMOVED:
...
INFO: 0 updated, 0 freshly installed, 43 removed and 0 unchanged
INFO: After this operation, 47.3 MB will be freed on the disk.
```

## Walkaround
Install elementary in _English (US)_ and choose the proper language on first startup.

## Platform Information
Tried on:
 * `elementaryos-6.0-stable.20210810.iso`
 * `elementaryos-6.0-stable.20210805-rc.iso`
 * `elementaryos-6.0-daily.20210430.iso` (Beta 2)

**Comment by m93a** [comment] 2021-08-11 19:41
Related issue on StackExchange: https://elementaryos.stackexchange.com/q/28242/19079

**Comment by gandalfthewhite19890404** [comment] 2021-08-14 05:46
Same thing if you're chosen Russian language.

**Comment by m93a** [comment] 2021-08-29 13:46
As described by another Czech user on StackExchange:

> I've tried it too and if I selected Czech language and US keyboard, instalation aborted at the begining. If I selected US language and czech keyboard it has stucked at 70 percent. In complete english it worked well.

    — [Jiří Florián](https://elementaryos.stackexchange.com/a/28666/19079)

**Comment by jcmvbkbc** [comment] 2021-09-09 01:37
When installing it in russian and installation hangs the following is visible in the /var/log/syslog:
https://hsto.org/webt/61/39/4a/61394aa112ad8061858211.png

**Comment by jeremypw** [comment] 2021-09-09 08:17
If it is limited to a particular language it is likely to be a translation error e.g. missing or changed placeholder. This will cause a crash.  Need to review the Czech `.po` file.

**Comment by jcmvbkbc** [comment] 2021-09-09 08:27
@jeremypw It looks like an issue in the code that reads output of the helper program (in that case, apparently apt), see 13th line from the bottom on the screenshot.

**Comment by jeremypw** [comment] 2021-09-09 08:31
There is at least one possible C format error in the Czech translation (https://l10n.elementary.io/translate/installer/installer/cs/?q=check:c_format).  I am not that familiar with the code of this project to say whether it causing this crash, but locale dependent problems are often down to translations.

**Comment by gandalfthewhite19890404** [comment] 2021-09-09 08:55
What is wrong with Russian?
Because I had same issue but with Russian language.

**Comment by jeremypw** [comment] 2021-09-09 11:29
Admittedly I could not find any C format problem with the Russian translation (although plenty of other languages had potential problems see https://l10n.elementary.io/checks/c_format/installer/installer/).  So the issue may be due to a translation problem in a helper program - or something else entirely I guess.  Looking at the log again there is a thread panicking during some sort of string manipulation ("byte 41 is not a char boundary ....") so maybe the code is not manipulating a string in locales with multibyte characters properly :shrug:

**Comment by jeremypw** [comment] 2021-09-09 11:42
@davidmhewitt Are you able to shed any light on this?

**Comment by davidmhewitt** [comment] 2021-09-09 13:43
This looks like it would be an issue with [distinst](https://github.com/pop-os/distinst) as it would be that calling on apt and other helper programs during the installation.

I'd like to do a bit more investigation on this before I say for sure though as we have diverged a bit from Pop!_OS on the way we use distinst vs them, especially around language handling.

**Comment by m93a** [comment] 2022-01-06 21:07
Bump, any update on this? Looks like it's still an issue :c

**Comment by kirush0280** [comment] 2022-01-15 19:26
the same problem with russian language, its hangs on 70% after apt purge

**Comment by ChildishGiant** [comment] 2022-02-07 21:22
![image](https://user-images.githubusercontent.com/13716824/152873933-544e9a7d-b913-4bcd-aa5e-8eebd4d042e4.png)
I'm installing OS 7 nightly (Admittedly on a VM) in UK l18n and have this issue too

**Comment by jcmvbkbc** [comment] 2022-02-28 14:57
> This looks like it would be an issue with [distinst](https://github.com/pop-os/distinst) as it would be that calling on apt and other helper programs during the installation.
> 
> I'd like to do a bit more investigation on this before I say for sure though as we have diverged a bit from Pop!_OS on the way we use distinst vs them, especially around language handling.

I've got some time to fiddle with this issue. I start installation in virtual machine (run it like this: `qemu-system-x86_64 -enable-kvm -m 2G -cdrom elementaryos-6.1-stable.20211218-rc.iso -hda disk`) and when graphical interface appears I switch to console and run distinst manually like this: `distinst -b /dev/sda -h test -r /cdrom/casper/filesystem.manifest-remove -s /cdrom/casper/filesystem.squashfs  -t /dev/sda:gpt -n /dev/sda:primary:start:end:ext4:mount=/ -l ru_RU.UTF-8`. This reliably reproduces the issue for me when I use distinst from the cdrom. However when I clone the mentioned distinst repository and build it myself (under debian 11) the resulting binary does not exhibit this behavior and distinst runs to the end (legitimately failing for a different reason at the end).

I have two questions: 1) how can I get debug info for the distinst binary that is shipped on a CD? and 2) is there a way to do a reproducible rebuild of the distinst (so I get the same binary that is on CD)?

**Comment by noangel** [comment] 2022-03-27 06:34
same error when selecting japanese language

**Comment by m93a** [comment] 2022-03-28 23:10
Just wanted to mention that I really like elementary and use it as my main OS, but I think that this install experience is just unacceptable. It's such an opaque problem and a horible first-time experience that it sincerely makes me feel bad for recommending elementary to other people. I know elementary has a small team and a lot of things to solve, but seriously – how is this not a priority?

**Comment by nazar1ua** [comment] 2023-01-12 10:36
@davidmhewitt

**Comment by 1280px** [comment] 2023-02-12 07:33
Fixed in OS7

**Comment by lenemter** [comment] 2023-02-12 08:50
I cannot reproduce the issue with Russian and Czech languages, so I assume it was fixed.

**Closed by lenemter** 2023-02-12 08:50 UTC
