### ISSUE TITLE
I'm asked about language again after rebooting from installer

### ISSUE THREAD

**Issue by Loreno10** [elementary/installer#516] opened 2021-05-02 09:39 UTC
**Describe the bug**
I just installed eOS (on VM via Boxes). After the reboot, the first thing I see is to choose the language again (see in _Screenshots_). I already did that during the Installation, so it seems that I should not have to do that again.

**To Reproduce**
1. Install eOS
2. Reboot as the installer says to do

**Expected behavior**
I should have to configure language stuff just once, during the installation.

**Screenshots**
Here's what I see after rebooting:
![image](https://user-images.githubusercontent.com/10273406/116808807-13e30f80-ab3b-11eb-8193-fc330cef3e44.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidmhewitt** [comment] 2021-05-02 09:46
This partly intentional. See "Every install is an OEM install": https://github.com/elementary/installer/wiki#every-install-is-an-oem-install

This is so a PC manufacturer or you can install an OS on the system and then give or sell it to someone and they can set it up as they like.

However, I believe there are plans to try and make some improvements here, so this sounds like a duplicate of: https://github.com/elementary/initial-setup/issues/51

**Closed by davidmhewitt** 2021-05-02 09:46 UTC

**Comment by Loreno10** [comment] 2021-05-02 09:51
Ok, I understand it. In such case, I think it does not make sense to ask about language/keyboard during the installation. Unless it is somehow required for the further steps?
