### ISSUE TITLE
Out of memory crash with gfxmode=auto

### ISSUE THREAD

**Issue by carniz** [elementary/installer#671] opened 2022-12-03 10:01 UTC
### What Happened?

The installer crashes on my laptop with a 4k monitor unless `gfxmode=auto` is changed to `gfxmode=800x600,auto` in /boot/grub/grub.cfg

### Steps to Reproduce

1. Boot from elementaryos-7.0-daily.20221201.iso restored to a freshly formatted USB drive
2. Select "Try or install"

At this point I get a "error: out of memory" message (followed by "press any key to continue"), and the next screen is the following:

![DSC_5528](https://user-images.githubusercontent.com/1648530/205377997-65c30cfa-372b-41a9-bb49-003915f1f358.JPG)

### Expected Behavior

I expect to be able to either try or install elementary :) 

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Dell Precision 5510 with 4k monitor (3840x2160)
BIOS 1.23.0 07/06/2022

**Comment by peteruithoven** [comment] 2023-02-15 15:34
Isn't this a duplicate of: https://github.com/elementary/installer/issues/542 ?

**Closed by peteruithoven** 2023-02-15 15:34 UTC
