### ISSUE TITLE
Installer not showing disk or partitions, can't install.

### ISSUE THREAD

**Issue by dvilelaf** [elementary/installer#617] opened 2021-08-27 18:08 UTC
## What happened

The new installer does not seem to recognize the ssd disk on a 2016 Macbook Pro. Trying to "erase and install" gives a "no enough space" message (and shows no disk), and the "custom install" option shows no disk. Gparted gives a "Invalid argument during the preparation for reading at /dev/nvme0n2" (I think that must be some minimal size recovery mac-related memory). The message can be ignored, and the partitions can be made in nvme0n1, but the installer does not recognize it. There's some snapshots [here](https://elementaryos.stackexchange.com/questions/28643/elementary-os-odin-installer-not-showing-partitions-on-macbook-pro-2016).

Note that I've checked that Ubuntu 20.04, 21.04 and elementary 5.1 recognize the disk correctly, so it seems that this could be the new installer's fault.

## Expected Behavior
The disk should be recognized to perform the installation.

## Steps to Reproduce
1. Launch the ISO
2. Select the disk
3. Install

## Platform Information
* elementary OS 6 Odin
* Macbook Pro 2016

**Comment by derkomai** [comment] 2021-08-28 00:36
Pop!_OS installer crashes just after selecting language, so I can't make it to the next screen.

**Comment by alicerunsonfedora** [comment] 2021-08-28 01:20
> Thanks for the report!
> 
> If possible, could you try booting a Pop!_OS iso and confirming whether or not the same issue exists there? We share the same installer backend (distinst) with them, so it would be good to confirm if the issue exists there too or if it's elementary specific.
> 
> Thanks!

I would love to, but I no longer use a 2017 MacBook Pro; instead, I use an M1 MacBook Air.

**Comment by BetaC4094** [comment] 2021-08-28 07:41
Same issue here, on my HP laptop. 
![photo_2021-08-28_07-40-39](https://user-images.githubusercontent.com/84247465/131210569-b1a8b816-091d-46f2-952f-bb0daa3b0848.jpg)

**Comment by derkomai** [comment] 2021-08-28 08:01
Pop!_OS installer crashes just after selecting language, so I can't make it to the next screen.

**Comment by davidmhewitt** [comment] 2021-08-28 08:53
Those that are experiencing this issue, if possible, please reproduce this issue by booting the iso again and getting to this blank screen. Then:

- Go back and enter "demo mode"
- Open the terminal
- Run `sudo journalctl > ~/log.txt`
- Upload `log.txt` in your home folder somewhere and attach/link it to this issue

**Comment by derkomai** [comment] 2021-08-28 11:07
> Those that are experiencing this issue, if possible, please reproduce this issue by booting the iso again and getting to this blank screen. Then:
> 
>     * Go back and enter "demo mode"
> 
>     * Open the terminal
> 
>     * Run `sudo journalctl > ~/log.txt`
> 
>     * Upload `log.txt` in your home folder somewhere and attach/link it to this issue

[Here you go](https://pastebin.com/RpmyP57E).

**Comment by BetaC4094** [comment] 2021-08-28 11:14
> Those that are experiencing this issue, if possible, please reproduce this issue by booting the iso again and getting to this blank screen. Then:
> 
> * Go back and enter "demo mode"
> * Open the terminal
> * Run `sudo journalctl > ~/log.txt`
> * Upload `log.txt` in your home folder somewhere and attach/link it to this issue

https://pastebin.com/YqBNBJx2

**Comment by gabriel-lucas** [comment] 2021-09-11 17:39
> Those that are experiencing this issue, if possible, please reproduce this issue by booting the iso again and getting to this blank screen. Then:
> 
>     * Go back and enter "demo mode"
> 
>     * Open the terminal
> 
>     * Run `sudo journalctl > ~/log.txt`
> 
>     * Upload `log.txt` in your home folder somewhere and attach/link it to this issue

Same here. Macbook air 13' Mid 2013

https://pastebin.com/gvWWWw92

**Comment by ImaCrea** [comment] 2021-09-22 22:51
thanks for the bug report, I'll wait a bit then before trying to install odin on my mb pro 2016 ^^

**Comment by smitheric95** [comment] 2021-10-03 01:06
I can confirm the same behavior on my MBP 13,1 (late 2016). The Pop!_OS 21.04 installer also crashes after selecting a language. 

This machine previously had Hera installed on it, and I don't recall any installation issues with that release.

**Comment by frank-malcov** [comment] 2021-10-30 20:48
Hi, i have the same problem, i have tried everything and the installer still not showing disk. GParted works just fine though too.

**Comment by FAdy-200** [comment] 2021-11-04 21:56
I had the same problem on my laptop, I fixed it by opening in demo mode and running `sudo apt update` then `sudo apt upgrade`, then I went back to the installer, and viola it works just fine

**Comment by FAdy-200** [comment] 2021-11-04 22:04
I have he same problem, i tried running in demo mode and doing `sudo apt upgrade` that made the drive show when i got back to the installer but it failed after that while unsquashing

**Comment by dvilelaf** [comment] 2021-11-05 10:08
> I have the same problem, i tried running in demo mode and doing `sudo apt upgrade` that made the drive show when i got back to the installer but it failed after that while unsquashing

I tried upgrading but it made no difference to me.

**Comment by FAdy-200** [comment] 2021-11-05 11:10
> > I have the same problem, i tried running in demo mode and doing `sudo apt upgrade` that made the drive show when i got back to the installer but it failed after that while unsquashing
> 
> I tried upgrading but it made no difference to me.

After backtracking everything,
I did:
Open demo mode
Mounting every partition 
`sudo apt update`
`sudo apt upgrade`
Trying to install again without unmounting anything 

It showed the drive then failed half way

**Comment by Gold3nF3nix** [comment] 2021-11-12 20:33
I can't see partitions too, but Pop os installer shows my partitions, but before that it crashes for about 5min.

**Comment by ajafov98** [comment] 2021-11-19 07:26
Try to change from SATA mode to AHCI in BIOS. Worked for me

**Comment by therajatshahare** [comment] 2021-11-27 02:33
![Pic 01](https://user-images.githubusercontent.com/72127077/143665337-c22fd97d-b88c-425a-b473-b1fe238f1fd5.jpeg)
Exactly same issue for me. I can't able to install Elementary OS in dual boot with manual option. It does not show me any disk of my laptop. Although when I click to the bottom left option Modify Partition it shows me all my disks but after modifying all partition when I apply it and go back to proceed the option of "Erase and Install" does not appear as because it does not show any disk. Changing from SATA mode to AHCI in BIOS? I don't think this is good option for many people.

**Comment by IsuruAkalanka** [comment] 2021-12-13 10:21
Hi, I also faced the same issue, is there any solutions.

**Comment by IsuruAkalanka** [comment] 2021-12-13 12:09
Hi I faced the same problem of not listing the available disca in the custom menu and I had 2 hdds in my machine so I remove all the other hdds only keeping the hdd which I am going to install elementry os and then the available disc was shown an I was able to successfully install elementry os 6

**Comment by yagyaxt1034** [comment] 2021-12-22 05:08
Just wanted to add I'm having a similar issue on my Acer Aspire TC-780 desktop, with a Kaby Lake i7. It's been present on every release since the April 30 RC build.

**Comment by anirvinn** [comment] 2021-12-23 05:33
Hello,

MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) Same Issue. Not showing partitions. Downloaded **Elementary OS 6.1 Jólnir.** Trying to "erase and install" gives a "no enough space" message (and shows no disk), and the "custom install" option shows no disk. Gparted gives a "Invalid argument during the preparation for reading at /dev/nvme0n2". The message can be ignored, and the partitions can be made in nvme0n1, but the installer does not recognize it. 

Here's the Log:
[log.txt](https://github.com/elementary/installer/files/7766896/log.txt)

**Comment by gthewarlock** [comment] 2021-12-28 08:32
Hello,

Hardware:
- Macbook Pro 2016 (A1708)
- SanDisk 3.1 Type USB-C Flashdrive with Elementary OS 6.1 Jólnir mounted

Issue:
- As mentioned above.
- Partitions not appearing. 
- Specifically /dev/nvme0n2 causing issues such as:
   "Invalid argument during the preparation for reading at /dev/nvme0n2"
- Unable to install Elementary OS.

Notes:
- Attempting to create a partition under /dev/nvme0n2 and selecting 'None' from alignment drop down prompts error dialogue stating 'Partition can not have -251 sectors,' while selecting 'Circle' doesn't cause an error dialogue.

**Comment by arshad10244** [comment] 2022-02-02 05:40
I had a similar issue when setting up a dual boot with Windows 10, and the issue was mounting the partitions in rw mode

remount didn't work so here is what i did that worked

1- Make sure you are booting in UEFI mode if your windows was installed in UEFI (grub installation would otherwise fail at the last step)
2- Use the demo mode and run ntfsfix on all ntfs partitions
3- open gparted and make your partitions (/ , swap & boot)
4- create a new folder in / (this will be on your elementary OS usb drive) and name it drive
5- run lsblk and note down your partitions for the drive you are installing os on. ( /sda1 /sda2)

repeat the steps 6-12 for all your partitions
6- umount /dev/your_partition
7- mount -o rw /dev/your_partition /drive
8- chmod 777 /drive
9- touch /drive/test.txt (just to test the drive is mounted in rw)
10- umount /dev/your_partition
11- open file explorer and open the partition from storage section (this will mount the drive in rw mode in /media)
12- delete test.txt

open the installer from the applications menu and install

**Comment by BrianMaoileoin** [comment] 2022-02-06 04:14
I had a similar issue. I was running OS 5 on a 2013 MacBook Pro. Upgraded to OS 6 no issues. I downloaded a few programmes then when I downloaded a battery management programme things stopped working, I could no longer download software. I attempted a clean install but it would not do that. I have tried a custom install but same issue. I downloaded the latest version od the OS 6 installer. I have taken a log.txt.
[log.txt](https://github.com/elementary/installer/files/8009408/log.txt)

**Comment by BrianMaoileoin** [comment] 2022-02-09 00:57
I have resolved the issue. I went into demo mode, opened Gparted, deleted all the partitions, wrote a new ext4 partition and clicked on "Install elementary" from applications whilst still in demo mode. Worked fine. I hope this helps others.

**Comment by sethleonard** [comment] 2022-03-09 00:10
I'm trying to dual-boot install on a MacBook Pro 2017 and having the same issue. I have been able to successfully install Ubuntu and Bodhi Linux. I've tried all the solutions here (new partitions, leave free space, install from demo, etc.) and never seen any partitions to choose from. Demo mode seems to work fine, though. Log attached.

[log.txt](https://github.com/elementary/installer/files/8210583/log.txt)

**Comment by tennox** [comment] 2022-05-07 22:31
Tried to bump on [slack #support](
https://elementarycommunity.slack.com/archives/C011F6MLGHJ/p1651962548097889)

**Comment by smitheric95** [comment] 2022-05-12 12:42
@davidmhewitt, is there any chance that this could be addressed in OS 7?

**Comment by simmo9000** [comment] 2022-05-17 08:31
Can confirm installer fails on a MacBook Pro 13,1 with 256G nvme :
Running io.elementary.installer from the terminal in the demo dumps this on clicking "Custom Install"

`** (io.elementary.installer:7583): CRITICAL **: 07:09:20.931: CheckView.vala:105: Unable to get disks list: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`

And this when clicking "Erase disk and Install"

 `** (io.elementary.installer:9521): CRITICAL **: 07:20:11.347: CheckView.vala:105: Unable to get disks list: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying  ** (io.elementary.installer:9521): CRITICAL **: 07:20:11.374: DiskView.vala:121: Unable to get disks list: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`

**Comment by tofutech** [comment] 2022-11-13 03:26
Has anyone solved this? Having the same issue on my 2017 Macbook Retina model. Gets to the Install screen, 'Erase Disk and Install" gives the Not Enough Space error and Partitioning not working either.

**Comment by tennox** [comment] 2022-11-13 10:00
Worked around similar to brian above, deleting partitions manually via gparted.
Then it works 💁‍♂️

**Comment by MichaelToniolo** [comment] 2023-01-05 14:35
I had this problem right now. I'll try @arshad10244 recommends

**Comment by aerocyber** [comment] 2023-04-11 12:33
I have proposed a PR that may potentially solve this issue. However, this issue can also be solved via a live disk.

Steps I followed that solved the issue:

- Boot into the live disk
- Install git
- Clone [this repository](https://github.com/elementary/installer)
- Edit `src/Helpers/InstallerDaemon.vala` and change the value of the variable `DBUS_TIMEOUT_MSEC` to a relatively higher one
- Compile the installer by the steps in `README.md`
- Replace the bundled installer using `sudo ninja install`
- Open `Applications > Install elementary` or run `io.elementary.installer`

**Closed** 2023-04-11 12:51 UTC

**Comment by MichaelToniolo** [comment] 2023-04-11 13:29
Guys I managed to solve this on my laptop as a tip that was mentioned in some forum I don't remember which one.
But I did the following steps:
1- I started the live boot and put try Elementary
2- I went to the pantheon file manager and mounted all the partitions that Pantheon showed me.
3- After that I went to the terminal and called the system installer with the following command
sudo io.elementary.installer
4- The installation menu opened to select the language and I followed the steps until I reached Custom Install (or Partition, I don't remember haha)
5- After that he listed the partitions and I managed to solve my question 100%.

**Comment by patx** [comment] 2023-04-11 23:49
If I update in AppCenter will this update the installer to the version that has the fixed merged in? I  am unable to build distinst on Live USB I run out of room before I can ninja install the installer from source. Please help, I would really love to be able to use Elementary OS on this Macbook 12 Retina (2017).

**Comment by hammPa** [comment] 2023-04-26 12:31
> Guys I managed to solve this on my laptop as a tip that was mentioned in some forum I don't remember which one. But I did the following steps: 1- I started the live boot and put try Elementary 2- I went to the pantheon file manager and mounted all the partitions that Pantheon showed me. 3- After that I went to the terminal and called the system installer with the following command sudo io.elementary.installer 4- The installation menu opened to select the language and I followed the steps until I reached Custom Install (or Partition, I don't remember haha) 5- After that he listed the partitions and I managed to solve my question 100%.

Thank you, after try this i can install elementary os 7 in my lenovo ideapad 330
