### ISSUE TITLE
The installer window is too large, making the "Next" button unreachable

### ISSUE THREAD

**Issue by sedeki** [elementary/installer#601] opened 2021-08-16 20:42 UTC
## What Happened
I'm trying to install Elementary in a VirtualBox, but the installer window is too big relative to available screen estate, so I cannot proceed to the next step. See the screenshot I have attached below.

I looked around in the pending PRs and I think this one might solve the issue (but I haven't verified it!): https://github.com/elementary/installer/pull/540

![elementary_screen](https://user-images.githubusercontent.com/4043059/129626307-c001834c-0dee-42b3-b3d5-0358a6d3e5d6.png)

## Platform Information
* I'm running the installer in the latest VirtualBox.
* Using latest Elementary ISO.
* I selected a generic Linux variant in VirtualBox (not Debian or any other distro)

**Comment by cassidyjames** [comment] 2021-08-16 20:50
Thanks for the report! This is a duplicate of #491. As a workaround, ensure EFI is enabled in VirtualBox, or drag the window with Super+Drag.

**Closed by cassidyjames** 2021-08-16 20:50 UTC
