### ISSUE TITLE
Installer not scaling in Virtual Box

### ISSUE THREAD

**Issue by lZzozZl** [elementary/installer#537] opened 2021-05-06 13:15 UTC
**Describe the bug**

The installer window is bigger than the new virtual box default screen size.
Using elementaryos-6.0-daily.20210430

**To Reproduce**

1. Create new Virtual Box VM ( default settings )
2. Choose elementaryos-6.0-daily.20210430.iso to start installation
3. Enjoy :D

**Expected behavior**

The installer window is not scaling right.
You cannot see the buttons for next and back.

(i manage to use TAB button on the keyboard to continue with the installation)

**Screenshots**

![image](https://user-images.githubusercontent.com/16064130/117303674-a52ceb80-ae85-11eb-9050-54a81154ffa1.png)
![image](https://user-images.githubusercontent.com/16064130/117304469-73685480-ae86-11eb-8000-d5c256b2a1c2.png)

**Additional context**

This happened on 2 different machines. One with Intel CPU and another with AMD cpu, gpu, ram, etc...

**Comment by nicekiwi** [comment] 2021-05-09 21:58
As a workaround, you can hit `Enter` on the boot countdown. Then press `Tab` to edit the boot params and add `vga=833` to set the minimum screen resolution to 1024x768 to get you into a working screen size for install/demo. :) 

https://linuxhint.com/set_screen_resolution_linux_kernel_boot/ 

Hope this helps.

**Comment by nicekiwi** [comment] 2021-05-09 23:39
This will however still boot into a smaller screen res after installation and I don't have a workaround for that yet. The Grub versions between the Live installer and the installed image appear to be different. 

![image](https://user-images.githubusercontent.com/738975/117590590-58e2f380-b184-11eb-88ab-832fb9828a67.png)

**Comment by mauricebauer** [comment] 2021-07-02 11:11
Still an issue with the current elementary OS 6 Beta 2 (Daily 20210615). Hope this can be solved for before the elementary OS 6 release.

**Comment by gandalfthewhite19890404** [comment] 2021-08-14 05:48
On release build - same thing.

**Comment by cassidyjames** [comment] 2021-08-17 02:18
This is a duplicate of #491

**Closed by cassidyjames** 2021-08-17 02:18 UTC
Labels: Status: Confirmed
