### ISSUE TITLE
There is an option to try demo mode, when you are already in demo mode

### ISSUE THREAD

**Issue by MrPotatoBobx** [elementary/installer#508] opened 2021-04-29 15:22 UTC
**Describe the bug**
When selecting demo mode in the installer, then opening it in demo mode, it shows an option for demo mode again, if pressed, it just restarts the session.

**To Reproduce**
1. Boot up daily iso
2. select language and keyboard layout
3. select " Try demo mode"
4. open installer in the demo session 

**Expected behavior**
When in demo mode, it should only show "clean install" and "advanced install"

**Screenshots**
![image](https://user-images.githubusercontent.com/63403023/116575844-b3c05380-a917-11eb-9ea2-25fd8d7f2b4d.png)

**Desktop (please complete the following information):**
 - OS: ElementaryOS
 - Browser: Epiphany 
 - Version: 6

**Comment by MrPotatoBobx** [comment] 2021-04-29 15:36
An alternative solution to just removing the option if its already in demo mode is to make it return to the original installation screen if the "install elementaryOS" app is open (as seen in https://github.com/elementary/installer/issues/176)

**Comment by cassidyjames** [comment] 2021-04-29 16:19
I think this is just a duplicate of #176, as it shouldn't open the installer in this session anyway.

**Closed** 2021-04-29 16:20 UTC
Labels: Status: Duplicate
