### ISSUE TITLE
Live iso does not boot directly in UEFI mode

### ISSUE THREAD

**Issue by theEndurance-del** [elementary/installer#592] opened 2021-08-11 12:02 UTC
# Description
Live ISO for elementary os 6 does not boot in UEFI mode unless manually configured.

# Steps to reproduce
- Burn the ISO as mentioned in the installation guide
- Reboot the system and enter the Boot Menu(F12 key for dell laptops)
- Select the USB drive containing the ISO

# Error
![20210811_170424](https://user-images.githubusercontent.com/57960301/129024381-ad3fc094-2b80-4b08-aaa9-e764eefe7f47.jpg)

# How I resolved it
- After entering the boot menu, go to the BIOS settings
- Go to boot sequence, and select add boot option
- Name it whatever you want and specify the path to FS1/EFI/boot/grubx64.efi
- Reboot
- Enter the boot menu and select the Boot option you created earlier
- Install the OS

## Note
I also tried burning the iso using `dd` but the outcome didn't change, so I had to resort to manually adding a boot entry and then deleting it after the install process was over

ISO: Elementary OS 6(Odin) Released on Tuesday 10, Aug, 2021 - 21:30 IST

**Comment by davidmhewitt** [comment] 2021-08-11 12:57
Thanks for the report!

This looks to be a duplicate of https://github.com/elementary/triage/issues/74 which is an upstream Ubuntu issue. I'll close this issue so we can keep track of it in one place. Thanks for detailing your workaround.

**Closed by davidmhewitt** 2021-08-11 12:57 UTC

**Comment by rafaelcn** [comment] 2021-08-11 18:16
Onde thing to do is to select the boot file after burning the image on the device. The following script code can do the job:

`efibootmgr --create --label Elementary --disk /dev/sda1 --loader "\EFI\boot\grubx64.efi"`

**Comment by theEndurance-del** [comment] 2021-08-12 02:09
> One thing to do is to select the boot file after burning the image on the device. The following script code can do the job:
> 
> `efibootmgr --create --label Elementary --disk /dev/sda1 --loader "\EFI\boot\grubx64.efi"` 

I guess the disk should point to `/dev/sdb` (sdb in my case because that was where the iso was burnt.

**Comment by rafaelcn** [comment] 2021-08-12 02:44
Yep, I totally forgot to generalize that. I'll edit it.
