### ISSUE TITLE
[eOS 8 RC1] Install window disappears after opening Custom Install option and no install proceeds

### ISSUE THREAD

**Issue by Hibryda** [elementary/installer#861] opened 2024-12-08 02:07 UTC
### What Happened?

While trying to install eOS 8 RC1 I stumbled upon a critical failure. The install wizard allowed for picking language and region, but when I've chosen Custom installation the window switched to it, started checking hardware and disappeared after around 2 seconds without a trace. No install proceeded.
I tried multiple times and even was able to open partition manager that showed on the Custom install window. This kept the window for longer (likely pausing hardware checking), though after closing partition manager the window closed without a trace as before.
Picking either Custom Install directly or Try Elementary and then run install results is the same behavior.

### Steps to Reproduce

1. Start installation from USB
2. Go through language, region, keyboard until reaching the choice of whether to try elementary, install erasing all or custom install and pick the latest option

### Expected Behavior

Should detect all the hardware and proceed with installation as usual

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

MSI Katana, 13th Gen Intel i7-13620H (16) @ 4.700GHz CPU, 64GB RAM, 2 GPUs, Intel on-board i915 and NVidia RTX 4060, two NVME drives, 2TB each with total of like 20 partitions and 3 OSes installed on the first drive.

**Comment by vjr** [comment] 2024-12-08 02:59
Breaking news! I was just trying with a daily ISO from Nov 20th... I noticed I DO NOT face this issue on the "first run" meaning I boot the ISO (via ventoy.net tool USB) and pick the defaults (language/keyboard) and pick the custom install option straight away without going into "Try Demo Mode" or anything else... It successfully lets me see all the partitions and pick the /boot/efi and select unused partition for formatting and install to / mount point etc...

If I click "back" and again select custom partitioning then it crashes (disappears) then I just go to TTY console by pressing CTRL+ALT+F1 and login user `elementary` (no password) then run `sudo service lightdm restart` then again on first attemtp it appears to work for me always, if I go back and again attempt custom partitioning it again crashes...

So not sure what's going on but have you tried to do a custom install as the very first thing after booting your ISO?

**Comment by Hibryda** [comment] 2024-12-08 23:52
@vjr Yes I did, to no avail. It's always the same.
Some additional observations:
- no `/etc/installer.log` or `/var/log/installer.log` (as you've suggested to check) are present. Only the empty `/var/log/installer/` directory.
- after switching to the console using `CTRL+ALT+F1` and logging with passwordless `elementary` user I'm getting lots of same errors from `sof-audio-pci-intel-tgl` printed. Maybe this is what hangs hardware detection (and should be immune to it).

**Comment by vjr** [comment] 2024-12-10 15:22
Might be a duplicate of https://github.com/elementary/installer/issues/848

**Closed** 2024-12-12 16:47 UTC
