### ISSUE TITLE
Window moves when resizing

### ISSUE THREAD

**Issue by eppixx** [elementary/installer#688] opened 2023-02-11 12:13 UTC
### What Happened?

When selecting the partitions, I noticed that resizing the window on the lower right it also moves the window in that direction (I resized because I have a lot of partitions and the description was too small).
After moving the window I could move the window back up with window+click+drag. But I don't think every user knows this, especially new ones.

The issue might also affecct other windows, but that I didn't test.

### Steps to Reproduce

1. Go through installation process
2. Select custom patitions option
3. resize window

### Expected Behavior

I expect the window to stay in place and grow to the size I move the mouse cursor to.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2023-02-13 08:25
This looks like a duplicate of #683

**Closed** 2023-02-15 15:25 UTC
