### ISSUE TITLE
Progress output expands window horizontally

### ISSUE THREAD

**Issue by codygarver** [elementary/installer#373] opened 2019-04-23 07:53 UTC
The distinst output causes the window to eventually become like 3000 chars wide. See attached screenshot.

![screenshot](https://user-images.githubusercontent.com/2166391/56564058-da9e5f00-6572-11e9-99c0-6fffe8513f60.png)

**Comment by mmstick** [comment] 2019-04-23 15:34
You need to rebase on the current version of the installer.

**Comment by cassidyjames** [comment] 2019-04-23 15:40
@codygarver specifically, this PR supposedly fixed it: https://github.com/pop-os/installer/pull/108

**Comment by cassidyjames** [comment] 2019-04-30 18:04
Duplicate of #257

**Closed** 2019-04-30 18:04 UTC
Labels: Status: Confirmed
