### ISSUE TITLE
Installing from Live-Boot requires password for elementary user

### ISSUE THREAD

**Issue by maulwurf87** [elementary/installer#439] opened 2020-08-12 08:28 UTC
**Describe the bug**
After booting in to the live environment  I tried to install elementary from the Applications Menu. An Authentication Menu
pops up and asks for the password of the user elementary, which the user does not have and cannot reset. The user cannot select another user.
Daily build: elementaryos-6.0-daily.20200812.iso

**To Reproduce**
1. Boot into live environment
2. Click on Applications
3. Click on Install elementary OS
4. Authentication window pops up

**Expected behavior**
Installer should launch, as we are in a live environment with no option for the user to set a password

**Desktop (please complete the following information):**
 - OS: Windows 10 - Hyper-V VM with daily build of elementary OS 6.0 20200812

**Additional context**
This issue may elevate into a bigger context, as the user cannot test anything in the live environment which requires sudo / root.
Please drop a note if I should open an issue for that too.

**Comment by cassidyjames** [comment] 2020-08-12 17:12
I believe this should be resolved by https://github.com/elementary/installer/issues/176

**Comment by maulwurf87** [comment] 2020-08-12 18:55
Thanks for the feedback. I will watch that issue and test if it's closed.

**Comment by cassidyjames** [comment] 2020-08-12 20:50
:+1: closing as a duplicate of #176

**Closed by cassidyjames** 2020-08-12 20:50 UTC
