### ISSUE TITLE
Keep log available on error page

### ISSUE THREAD

**Issue by jackpot51** [elementary/installer#234] opened 2018-02-22 20:46 UTC
Right now, when an error happens, the log goes away meaning it is not easy to find out what happened.

**Comment by cassidyjames** [comment] 2018-02-22 21:06
This… makes sense to me. If you get catastrophic failure, we should give the user that log in case it has something important in it. I think it's still useful on the progress page, though, right? I.e. in case a specific process is taking a while.

**Comment by isantop** [comment] 2018-02-22 22:36
I'd agreed that it is still useful on the status page. And it probably isn't useful on the success page.

**Comment by cassidyjames** [comment] 2018-03-20 18:36
I just realized this was a duplicate of #179

**Closed by cassidyjames** 2018-03-20 18:36 UTC
Labels: Status: Duplicate
