### ISSUE TITLE
Different keyboard layouts can not be tested on KeyboardLayoutView page

### ISSUE THREAD

**Issue by brs17** [elementary/installer#253] opened 2018-03-09 23:45 UTC
When selecting a keyboard that isn't the standard US QWERTY keyboard, typing in the `Type to test your layout` input still outputs in QWERTY.

I have tried both Spanish and English dvorak keyboard layouts.

**Comment by joshuajaharwood** [comment] 2020-09-08 20:19
The same happens when testing UK QWERTY on 6.0 Next, build 8/9/20; I'm stuck on the US layout. This is fixed once we boot from the install drive into user setup.

**Comment by danrabbit** [comment] 2020-09-08 21:53
Hm, this should have been fixed in https://github.com/elementary/installer/pull/443. It looks like the latest build of installer finished less than 20 hours ago, so this fix might be in the September 9th daily OS image

**Comment by carniz** [comment] 2020-09-14 15:23
Still seeing this with the 20200914 build when trying to use a Swedish keyboard layout.

**Comment by carniz** [comment] 2020-11-28 12:56
...and still present in elementaryos-6.0-daily.20201128.iso, so I guess [#443](https://github.com/elementary/installer/pull/443) didn't do the trick :/

**Comment by carniz** [comment] 2021-01-19 18:53
...and 2 months later it's still there (tested elementaryos-6.0-daily.20210118.iso)

**Comment by carniz** [comment] 2021-01-31 10:52
To be clarified: the issue is still there in the pre-restart phase of the installation (i.e. prior to setting up a user):

![VirtualBox_elementary6install_31_01_2021_11_31_44](https://user-images.githubusercontent.com/1648530/106381643-81f02d00-63ba-11eb-8ab1-e521e6f7618b.png)

After the restart the keyboard layout works as it should:

![VirtualBox_elementary6install_31_01_2021_11_45_20](https://user-images.githubusercontent.com/1648530/106381663-a51adc80-63ba-11eb-997f-8ddc31e896f3.png)

**Closed** 2021-02-27 16:18 UTC
