### ISSUE TITLE
Increase default /boot size

### ISSUE THREAD

**Issue by gvansanden** [elementary/installer#506] opened 2021-04-21 07:23 UTC
**Describe the bug**
/boot is on a separate FS that is 512MB in size.  Ubuntu 20.04 itself uses 1GB because the new kernels are too big.  This means you will quickly run out of space there and updates will break

**To Reproduce**
1. Install Elementary 6
2. Check /boot

**Desktop (please complete the following information):**
 - OS: Elementary OS 6 preview

**Comment by aral** [comment] 2021-11-30 11:42
This is now causing AppCenter operating system update failures for a number of people, including me (see linked-to issues, above).

**Comment by aral** [comment] 2021-11-30 11:52
To confirm that you are out of disk space in _/boot/_:

```shell
df -h | grep /boot
```

Workaround, based on [this article](https://www.jamescoyle.net/how-to/1974-how-to-fix-a-full-boot-partition-on-linux), until this is updated in the installer, that worked for me:

(Check the Linux kernel versions you have installed and tweak accordingly. Make sure you leave the latest kernel as well as the one after that that failed to install properly alone. In my case, this was_5.11.0-38-generic_ and _5.11.0-41-generic_. I also left _5.11.0-37-generic_ alone until after 41 installed correctly, out of an abundance of caution.)

```shell
sudo rm /boot/*-5.11.0-34*
sudo rm /boot/*-5.11.0-27*
sudo apt install -f
```

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-30 15:32
Checked the installed Kernels running `dpkg --list 'linux-image*'`

```
un  linux-image                            <none>                <none>       (no description available)
ii  linux-image-5.11.0-40-generic          5.11.0-40.44~20.04.2  amd64        Signed kernel image generic
ii  linux-image-5.11.0-41-generic          5.11.0-41.45~20.04.1  amd64        Signed kernel image generic
ii  linux-image-generic-hwe-20.04          5.11.0.41.45~20.04.19 amd64        Generic Linux kernel image
un  linux-image-unsigned-5.11.0-40-generic <none>                <none>       (no description available)
un  linux-image-unsigned-5.11.0-41-generic <none>                <none>       (no description available)
```

Which of them can I remove safely? Especially the linux-image-unsigned irritate me and the difference between `Signed kernel image generic` and `Generic Linux kernel image` are not clear to me yet.

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-30 15:33
Thanks for the hint ChildishGiant!

**Comment by ChildishGiant** [comment] 2021-11-30 15:54
To delete kernels I used [Mainline](https://ubuntuhandbook.org/index.php/2020/08/mainline-install-latest-kernel-ubuntu-linux-mint/)

**Comment by cassidyjames** [comment] 2021-11-30 18:57
I agree this is probably a good idea, but the root cause (https://github.com/elementary/triage/issues/91) also needs to be addressed by automatically cleaning up old kernels.

**Comment by danrabbit** [comment] 2021-12-13 22:45
So it looks like you only get the 512MB partition if you're doing encryption: https://github.com/elementary/installer/blob/2691d62a9889e4522753e1a8296691e1f2ad14c5/daemon/Daemon.vala#L284

I can't confirm ever running out of space without encryption. Can everyone experiencing this issue verify that they are using full disk encryption?

**Comment by 4jNsY6fCVqZv** [comment] 2021-12-14 01:43
I can confirm that I have enabled LUKS disk encryption by using the installer.

**Comment by ChildishGiant** [comment] 2021-12-15 09:14
Yep, both the instances I've ran into this I have been using full disk encryption

**Comment by aral** [comment] 2021-12-15 13:31
Ditto on full-disk encryption.

Long-term solution, of course, is to remove older kernels.

**Comment by danrabbit** [comment] 2021-12-17 22:24
Alright, we doubled the size of the boot for encrypted installs, so I'm gonna close this issue. We're still tracking autoremove at https://github.com/elementary/triage/issues/91

**Closed by danrabbit** 2021-12-17 22:24 UTC
Labels: Priority: Wishlist, Status: Confirmed

**Comment by 4jNsY6fCVqZv** [comment] 2021-12-19 08:00
The changes are then available for new installations and not for existing installations, right?

**Comment by danrabbit** [comment] 2021-12-19 19:29
@4jNsY6fCVqZv that's correct, we wouldn't be able to change your partitions in an update
