### ISSUE TITLE
Too Large Menu for Setup in VMware VM

### ISSUE THREAD

**Issue by SpaceChang** [elementary/installer#638] opened 2022-01-14 16:26 UTC
### What Happened?

Windows was incomplete while installing in VMware VM.

### Steps to Reproduce

1. New VMware Workstation VM
2. Setup with ISO
3. See the broken windows

### Expected Behavior

See complete Window

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![b2](https://user-images.githubusercontent.com/97750596/149549901-e2093b5d-ae28-4cc3-9683-56368b91cc04.PNG)

**Comment by cassidyjames** [comment] 2022-01-14 18:46
Thanks for reporting this! However, it's a duplicate of https://github.com/elementary/installer/issues/491

**Closed by cassidyjames** 2022-01-14 18:46 UTC
