### ISSUE TITLE
Please restore old installer screen size when installing in virtual box

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/installer#653] opened 2022-09-17 16:10 UTC
### Problem

Since elementary 6.0, the screen size in the installer is messed up when I start the ISO image in a VM to install elemenatry.
This makes it necessary to trial-and-error with the "tab" key to find the right UI controls to step through the installation as I am used to. 

Getting to the right config is especially challenging when you want to choose encrypted disk in the installation process.

### Proposal

Make the installer fit into the screen of a vanilla virtual box installation

**Comment by danrabbit** [comment] 2022-09-19 18:46
Closing as a duplicate of #491

**Closed by danrabbit** 2022-09-19 18:46 UTC
