### ISSUE TITLE
Graphics drivers step in installer

### ISSUE THREAD

**Issue by donadigo** [elementary/installer#330] opened 2018-05-19 21:22 UTC
Since we can't include drivers in the ISO by default, we should design and create another step in the installer that would let the user to automatically download and install these as part of the installation. In the step we could also mention that drivers can be installed later in AppCenter in the installed tab. This could make the drivers more discoverable to the user.

**Comment by cassidyjames** [comment] 2018-05-19 21:25
Duplicate of #47

**Closed by cassidyjames** 2018-05-19 21:25 UTC
